name: Metrics

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          template: classic
          base: "header, activity"
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          config_timezone: Europe/Moscow
          config_display: large
          extras_css: |
            svg { color: #999999 !important; }
            h1, h2, h3 { color: #CCCCCC !important; }
            .field svg { fill: #666666 !important; }
            .field * { color: inherit !important; }